---

cf-params: &cf-params
      CF_API_URL: ((cf_api_url))
      CF_USER_NAME: ((cf_user_name))
      CF_PASSWORD: ((cf_password))
      CF_ORG: ((cf_org))
      CF_SKIP_SSL: ((cf_skip_ssl))
      CF_SPACE: ((cf_space))
      CF_APP_DOMAIN: ((cf_app_domain))

resources:

- name: source
  type: git
  source:
    uri: https://github.com/cloudfoundry/developer-training-class-apps.git
    branch: master
    paths: [web-ui/*,ci/solution_setup.sh]

- name: uaa-war
  type: s3
  source:
    bucket: ((assets_bucket_name))
    region_name: ((assets_bucket_region))
    versioned_file: uaa.war
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))

- name: uaa-manifest
  type: s3
  source:
    bucket: ((assets_bucket_name))
    region_name: ((assets_bucket_region))
    versioned_file: uaa-manifest.yml
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))

- name: rest-data-service-jar
  type: s3
  source:
    bucket: ((assets_bucket_name))
    region_name: ((assets_bucket_region))
    versioned_file: rest-data-service.jar
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))

- name: web-ui-zip
  type: s3
  source:
    bucket: ((assets_bucket_name))
    region_name: ((assets_bucket_region))
    versioned_file: web-ui.zip
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))

jobs:

- name: unit-test
  serial: true
  plan:
  - get: source
    trigger: true
  - task: unit-test-web-ui
    file: source/web-ui/ci/tasks/unit-tests.yml

- name: integration-test
  serial: true
  plan:
  - aggregate:
    - get: source
      passed: [unit-test]
      trigger: true
    - get: uaa-war
      trigger: true
    - get: uaa-manifest
      trigger: true
    - get: rest-data-service-jar
      trigger: true
  - task: deploy
    file: source/web-ui/ci/tasks/deploy.yml
    params: *cf-params
    on_failure:
      task: cleanup-web-ui
      file: source/web-ui/ci/tasks/cleanup.yml
      params: *cf-params
  - task: system-test-web-ui
    file: source/web-ui/ci/tasks/system-tests.yml
    params: *cf-params
    on_failure:
      task: cleanup-web-ui
      file: source/web-ui/ci/tasks/cleanup.yml
      params: *cf-params

- name: package
  serial: true
  plan:
  - get: source
    passed: [integration-test]
    trigger: true
  - task: create-zip
    file: source/web-ui/ci/tasks/create-zip.yml
  - put: web-ui-zip
    params:
      file: artifacts/web-ui.zip


- name: cleanup-web-ui
  plan:
  - get: source
    passed: [integration-test]
    trigger: true
  - task: cleanup-web-ui
    file: source/web-ui/ci/tasks/cleanup.yml
    params: *cf-params
