---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli
    tag: 'latest'

inputs:
- name: source
- name: uaa-war
- name: uaa-manifest
- name: rest-data-service-jar

run:
  path: source/web-ui/ci/tasks/deploy.sh

params:
  CF_API_URL:
  CF_USER_NAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SKIP_SSL:
  CF_SPACE:
  CF_APP_DOMAIN:
