# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed

Metrics/LineLength:
  Max: 180

Metrics/BlockLength:
  Exclude:
    - 'spec/*.rb'
